
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservice
  name: myservice
  namespace: production
spec:
  ports:
  - name: bakehouseport
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bakehouse
  type: LoadBalancer
